### ISSUE TITLE
Не запускается jar file

### ISSUE THREAD

**Issue by YuliyaGer** [YuliyaGer/SQL#1]
У меня Windows 7, 64 бит. Docker и Docker-compose нет. 
1. Установила MySQL server на компьютер (скачала установщик весит 415,1M по этой ссылке https://dev.mysql.com/downloads/windows/installer/8.0.html );
2. Установила на все соглашаясь, как в шагах: https://wiki.merionet.ru/servernye-resheniya/12/ustanovka-mysql-servera-na-windows-10/ , только пользователь yuliya и пароль мой
3. Затем создала базу данных, и внесла в нее таблички из файла схема: https://docs.google.com/document/d/1xeUqI3IjZQdRE1tgmV_aA6pNopXrChtC1LebCNN8XCs/edit?usp=sharing
4. В Idea создала проект SQL, подключила зависимости, прописала путь к схеме, прописала properties (все выгрузила на GitHub там можно увидеть).
5. Пытаюсь запустить jar файл командой (java -jar app-deadline.jar -P:jdbc:mysql://localhost:3306/db -P:jdbc.user=yuliya -P:jdbc.password=1
 ), где значения флагов соответствуют значениям в properties.
Возникает ошибка с логами:
![image](https://user-images.githubusercontent.com/56927385/72175499-58e6ae00-33ed-11ea-96f2-7e6b3e79b798.png)
![image](https://user-images.githubusercontent.com/56927385/72175546-7287f580-33ed-11ea-973a-2633d810593a.png)

![image](https://user-images.githubusercontent.com/56927385/72175596-8a5f7980-33ed-11ea-840f-f71644e54504.png)

6. Помимо этого, есть еще проблема. Так как у меня нет docker на компе, я не понимаю последовательность моих действий в принципе. Вот если бы jar файл у меня запустился и я написала все тесты в Idea, мне потом надо было бы play with docker пользоваться и его как то подключать? А SQL который у меня на компе теперь,как во всю эту схему вписать?

**Comment by ArRomanov** [comment]
application.properties вам не нужен, его можно удалить и забыть.
Приложение не может подключиться к базе данных под пользователем yuliya. Возможно, вы передаете при запуске неверный пароль - -P:jdbc.password=1. Вместо 1 вам нужно передать тот пароль, который вы задали при установки mysql, когда создавали пользователя yuliya

**Comment by YuliyaGer** [comment]
Пароль я, действительно, передавала не от SQL. Но когда я его изменила, ошибка осталась та же. А это значение  -P:jdbc:mysql://localhost:3306/db, я не меняю? Когда я в SQL создавала базу то назвала ее db.

**Comment by ArRomanov** [comment]
Вы пробовали самостоятельно подключаться к базе данных? Например, настроить подключение через dbeaver. Если еще не пробовали, то попробуйте, чтобы убедиться, что вы используете нужные данные для подключения.
